DROP TABLE IF EXISTS fruit;
DROP TABLE IF EXISTS farmer;

CREATE TABLE farmer (
    id bigint generated by default as identity
    (START WITH 0L
    INCREMENT BY 1),
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE fruit (
    id bigint generated by default as identity
    (START WITH 0L
    INCREMENT BY 1),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    farmer_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_fruit_farmer
        FOREIGN KEY (farmer_id) REFERENCES farmer (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

INSERT INTO farmer (id, name, location) VALUES
    (1L, 'Farmer Rick', 'Sa Pobla'),
    (2L, 'Morty Vegan', 'Es Vivero');

INSERT INTO fruit (id, name, description, farmer_id) VALUES
    (1L, 'Apple', 'Winter fruit', 1L),
    (2L, 'Pineapple', 'Tropical fruit', 2L);